version: "3.5"
services:
  database:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1 --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
  processmaker:
    image: emaco/processmaker:3.5.7
    ports:
      - 8081:80
    volumes:
      - processmaker:/srv/processmaker/shared/sites/workflow
    restart: always
    depends_on:
      - database
volumes:
  database:
  processmaker:
